### ISSUE TITLE
TS errors on v8beta

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1173]
When updating aestudio to v8beta, I stumbled across these TS errors in the SDK:

```ts
ERROR in node_modules/@aeternity/aepp-sdk/es/tx/builder/index.d.ts:37:65 - error TS2339: Property 'excludeKeys' does not exist on type 'any[]'.

37 export function validateParams(params: Object, schema: any[], { excludeKeys }: any[]): Object;
                                                                   ~~~~~~~~~~~
node_modules/@aeternity/aepp-sdk/es/tx/builder/index.d.ts:75:78 - error TS2339: Property 'vsn' does not exist on type '{ excludeKeys?: Object; prefix?: string; }'.

75 export function buildTx(params: Object, type: string, { excludeKeys, prefix, vsn, denomination }?: {
                                                                                ~~~
node_modules/@aeternity/aepp-sdk/es/tx/builder/index.d.ts:75:83 - error TS2339: Property 'denomination' does not exist on type '{ excludeKeys?: Object; prefix?: string; }'.

75 export function buildTx(params: Object, type: string, { excludeKeys, prefix, vsn, denomination }?: {
                                                                                     ~~~~~~~~~~~~
```

you can reproduce here: https://github.com/aeternity/fire-editor/tree/iris-integration-test

**Comment by mradkov** [comment]
Is this still reproducible?

**Comment by nikita-fuchs** [comment]
seems solved.

**Comment by davidyuk** [comment]
should be fixed by 572d19f5ae6bd549c92a1a37452c0270490b9f6e

**Comment by marc0olo** [comment]
@nikita-fuchs you reopened the issue. is it still reproducable for you?

**Comment by subhod-i** [comment]
@nikita-fuchs I am trying to screen all the issues. Let us know if this issue still persists?

**Comment by nikita-fuchs** [comment]
nothing I came across anymore lately, closing.
