### PR TITLE
Fix BrowserRuntime in Firefox and pre-release fixes

### LINKED ISSUE #1734: Aepp Wallet communication is broken on Firefox browser
As described in the title

**To Reproduce**
Build the web wallet extension from the examples and try to connect an aepp.

**Expected behavior**
Successful communication is between aepp and weallet

**Please tell us about your environment:**
SDK version: 12.1.3
Aepp: Superhero Dex

Error message:
`TypeError: this.port.onMessage.hasListeners is not a function` originating from https://github.com/aeternity/aepp-sdk-js/blob/6a6e9f317a4f4fbc09ff520b474fc72b1a1066b5/src/aepp-wallet-communication/connection/BrowserRuntime.ts#L58

Firefox environment doesn't have `hasListeners` method as compared to the Chromium browsers.

### PR DESCRIPTION
**Pull request by davidyuk**
closes #1734 

The bug was introduced in https://github.com/aeternity/aepp-sdk-js/commit/19cb42fd2766bc9bcd90cfb04b5f03f00c0c7389#diff-36d07e359d2d2e15c6138f9cb478e39dc89c891e0bab325ba8508f32e1478063L90

Related fix in webextension-polyfill types https://github.com/Lusito/webextension-polyfill-ts/pull/88

This PR is supported by the Æternity Crypto Foundation

### CODE REVIEW

File: src/aepp-wallet-communication/connection/BrowserRuntime.ts [hunk 1]
```diff
@@ -34,19 +37,27 @@ export default class BrowserRuntimeConnection extends BrowserConnection {
...
+    this.#listeners = [
+      (message, port) => {
+        this.receiveMessage(message);
+        // TODO: make `origin` optional because sender url is not available on aepp side
+        onMessage(message, port.sender?.url ?? '', port);
+      },
+      onDisconnect,
+    ];
+    this.port.onMessage.addListener(this.#listeners[0]);
+    this.port.onDisconnect.addListener(this.#listeners[1]);
```
Comment (davidyuk) [inline src/aepp-wallet-communication/connection/BrowserRuntime.ts:60]: This needs to be refactored, this code actually binds listeners, not connecting no anything

**Review by subhod-i — APPROVED** [review]
